/*
 * Enterprise Reporting APIs (preview)
 * The Reporting APIs enable Enterprise Azure customers to programmatically pull consumption and billing data into preferred data analysis tools. Generate API Key on Enterprise portal and follow the tutorial under Help - Reporting APIs. The first section under this help article explains how to generate\\retrieve the API key for the specified enrollment. <a href=\"https://docs.microsoft.com/en-us/azure/billing/billing-enterprise-api\" data-linktype=\"external\">Billing Enterprise API official documentation</a>
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * BalanceSummaryV1
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-04T20:02:06.353Z")
public class BalanceSummaryV1 {
  @SerializedName("id")
  private String id = null;

  @SerializedName("billingPeriodId")
  private String billingPeriodId = null;

  @SerializedName("currencyCode")
  private String currencyCode = null;

  @SerializedName("beginningBalance")
  private Double beginningBalance = null;

  @SerializedName("endingBalance")
  private Double endingBalance = null;

  @SerializedName("newPurchases")
  private Double newPurchases = null;

  @SerializedName("adjustments")
  private Double adjustments = null;

  @SerializedName("utilized")
  private Double utilized = null;

  @SerializedName("serviceOverage")
  private Double serviceOverage = null;

  @SerializedName("chargesBilledSeparately")
  private Double chargesBilledSeparately = null;

  @SerializedName("totalOverage")
  private Double totalOverage = null;

  @SerializedName("totalUsage")
  private Double totalUsage = null;

  @SerializedName("azureMarketplaceServiceCharges")
  private Double azureMarketplaceServiceCharges = null;

  @SerializedName("newPurchasesDetails")
  private List<DetailsV1> newPurchasesDetails = null;

  @SerializedName("adjustmentDetails")
  private List<DetailsV1> adjustmentDetails = null;

  public BalanceSummaryV1 id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public BalanceSummaryV1 billingPeriodId(String billingPeriodId) {
    this.billingPeriodId = billingPeriodId;
    return this;
  }

   /**
   * Get billingPeriodId
   * @return billingPeriodId
  **/
  @ApiModelProperty(value = "")
  public String getBillingPeriodId() {
    return billingPeriodId;
  }

  public void setBillingPeriodId(String billingPeriodId) {
    this.billingPeriodId = billingPeriodId;
  }

  public BalanceSummaryV1 currencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
    return this;
  }

   /**
   * Get currencyCode
   * @return currencyCode
  **/
  @ApiModelProperty(value = "")
  public String getCurrencyCode() {
    return currencyCode;
  }

  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }

  public BalanceSummaryV1 beginningBalance(Double beginningBalance) {
    this.beginningBalance = beginningBalance;
    return this;
  }

   /**
   * Get beginningBalance
   * @return beginningBalance
  **/
  @ApiModelProperty(value = "")
  public Double getBeginningBalance() {
    return beginningBalance;
  }

  public void setBeginningBalance(Double beginningBalance) {
    this.beginningBalance = beginningBalance;
  }

  public BalanceSummaryV1 endingBalance(Double endingBalance) {
    this.endingBalance = endingBalance;
    return this;
  }

   /**
   * Get endingBalance
   * @return endingBalance
  **/
  @ApiModelProperty(value = "")
  public Double getEndingBalance() {
    return endingBalance;
  }

  public void setEndingBalance(Double endingBalance) {
    this.endingBalance = endingBalance;
  }

  public BalanceSummaryV1 newPurchases(Double newPurchases) {
    this.newPurchases = newPurchases;
    return this;
  }

   /**
   * Get newPurchases
   * @return newPurchases
  **/
  @ApiModelProperty(value = "")
  public Double getNewPurchases() {
    return newPurchases;
  }

  public void setNewPurchases(Double newPurchases) {
    this.newPurchases = newPurchases;
  }

  public BalanceSummaryV1 adjustments(Double adjustments) {
    this.adjustments = adjustments;
    return this;
  }

   /**
   * Get adjustments
   * @return adjustments
  **/
  @ApiModelProperty(value = "")
  public Double getAdjustments() {
    return adjustments;
  }

  public void setAdjustments(Double adjustments) {
    this.adjustments = adjustments;
  }

  public BalanceSummaryV1 utilized(Double utilized) {
    this.utilized = utilized;
    return this;
  }

   /**
   * Get utilized
   * @return utilized
  **/
  @ApiModelProperty(value = "")
  public Double getUtilized() {
    return utilized;
  }

  public void setUtilized(Double utilized) {
    this.utilized = utilized;
  }

  public BalanceSummaryV1 serviceOverage(Double serviceOverage) {
    this.serviceOverage = serviceOverage;
    return this;
  }

   /**
   * Get serviceOverage
   * @return serviceOverage
  **/
  @ApiModelProperty(value = "")
  public Double getServiceOverage() {
    return serviceOverage;
  }

  public void setServiceOverage(Double serviceOverage) {
    this.serviceOverage = serviceOverage;
  }

  public BalanceSummaryV1 chargesBilledSeparately(Double chargesBilledSeparately) {
    this.chargesBilledSeparately = chargesBilledSeparately;
    return this;
  }

   /**
   * Get chargesBilledSeparately
   * @return chargesBilledSeparately
  **/
  @ApiModelProperty(value = "")
  public Double getChargesBilledSeparately() {
    return chargesBilledSeparately;
  }

  public void setChargesBilledSeparately(Double chargesBilledSeparately) {
    this.chargesBilledSeparately = chargesBilledSeparately;
  }

  public BalanceSummaryV1 totalOverage(Double totalOverage) {
    this.totalOverage = totalOverage;
    return this;
  }

   /**
   * Get totalOverage
   * @return totalOverage
  **/
  @ApiModelProperty(value = "")
  public Double getTotalOverage() {
    return totalOverage;
  }

  public void setTotalOverage(Double totalOverage) {
    this.totalOverage = totalOverage;
  }

  public BalanceSummaryV1 totalUsage(Double totalUsage) {
    this.totalUsage = totalUsage;
    return this;
  }

   /**
   * Get totalUsage
   * @return totalUsage
  **/
  @ApiModelProperty(value = "")
  public Double getTotalUsage() {
    return totalUsage;
  }

  public void setTotalUsage(Double totalUsage) {
    this.totalUsage = totalUsage;
  }

  public BalanceSummaryV1 azureMarketplaceServiceCharges(Double azureMarketplaceServiceCharges) {
    this.azureMarketplaceServiceCharges = azureMarketplaceServiceCharges;
    return this;
  }

   /**
   * Get azureMarketplaceServiceCharges
   * @return azureMarketplaceServiceCharges
  **/
  @ApiModelProperty(value = "")
  public Double getAzureMarketplaceServiceCharges() {
    return azureMarketplaceServiceCharges;
  }

  public void setAzureMarketplaceServiceCharges(Double azureMarketplaceServiceCharges) {
    this.azureMarketplaceServiceCharges = azureMarketplaceServiceCharges;
  }

  public BalanceSummaryV1 newPurchasesDetails(List<DetailsV1> newPurchasesDetails) {
    this.newPurchasesDetails = newPurchasesDetails;
    return this;
  }

  public BalanceSummaryV1 addNewPurchasesDetailsItem(DetailsV1 newPurchasesDetailsItem) {
    if (this.newPurchasesDetails == null) {
      this.newPurchasesDetails = new ArrayList<DetailsV1>();
    }
    this.newPurchasesDetails.add(newPurchasesDetailsItem);
    return this;
  }

   /**
   * Get newPurchasesDetails
   * @return newPurchasesDetails
  **/
  @ApiModelProperty(value = "")
  public List<DetailsV1> getNewPurchasesDetails() {
    return newPurchasesDetails;
  }

  public void setNewPurchasesDetails(List<DetailsV1> newPurchasesDetails) {
    this.newPurchasesDetails = newPurchasesDetails;
  }

  public BalanceSummaryV1 adjustmentDetails(List<DetailsV1> adjustmentDetails) {
    this.adjustmentDetails = adjustmentDetails;
    return this;
  }

  public BalanceSummaryV1 addAdjustmentDetailsItem(DetailsV1 adjustmentDetailsItem) {
    if (this.adjustmentDetails == null) {
      this.adjustmentDetails = new ArrayList<DetailsV1>();
    }
    this.adjustmentDetails.add(adjustmentDetailsItem);
    return this;
  }

   /**
   * Get adjustmentDetails
   * @return adjustmentDetails
  **/
  @ApiModelProperty(value = "")
  public List<DetailsV1> getAdjustmentDetails() {
    return adjustmentDetails;
  }

  public void setAdjustmentDetails(List<DetailsV1> adjustmentDetails) {
    this.adjustmentDetails = adjustmentDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BalanceSummaryV1 balanceSummaryV1 = (BalanceSummaryV1) o;
    return Objects.equals(this.id, balanceSummaryV1.id) &&
        Objects.equals(this.billingPeriodId, balanceSummaryV1.billingPeriodId) &&
        Objects.equals(this.currencyCode, balanceSummaryV1.currencyCode) &&
        Objects.equals(this.beginningBalance, balanceSummaryV1.beginningBalance) &&
        Objects.equals(this.endingBalance, balanceSummaryV1.endingBalance) &&
        Objects.equals(this.newPurchases, balanceSummaryV1.newPurchases) &&
        Objects.equals(this.adjustments, balanceSummaryV1.adjustments) &&
        Objects.equals(this.utilized, balanceSummaryV1.utilized) &&
        Objects.equals(this.serviceOverage, balanceSummaryV1.serviceOverage) &&
        Objects.equals(this.chargesBilledSeparately, balanceSummaryV1.chargesBilledSeparately) &&
        Objects.equals(this.totalOverage, balanceSummaryV1.totalOverage) &&
        Objects.equals(this.totalUsage, balanceSummaryV1.totalUsage) &&
        Objects.equals(this.azureMarketplaceServiceCharges, balanceSummaryV1.azureMarketplaceServiceCharges) &&
        Objects.equals(this.newPurchasesDetails, balanceSummaryV1.newPurchasesDetails) &&
        Objects.equals(this.adjustmentDetails, balanceSummaryV1.adjustmentDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, billingPeriodId, currencyCode, beginningBalance, endingBalance, newPurchases, adjustments, utilized, serviceOverage, chargesBilledSeparately, totalOverage, totalUsage, azureMarketplaceServiceCharges, newPurchasesDetails, adjustmentDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BalanceSummaryV1 {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    billingPeriodId: ").append(toIndentedString(billingPeriodId)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("    beginningBalance: ").append(toIndentedString(beginningBalance)).append("\n");
    sb.append("    endingBalance: ").append(toIndentedString(endingBalance)).append("\n");
    sb.append("    newPurchases: ").append(toIndentedString(newPurchases)).append("\n");
    sb.append("    adjustments: ").append(toIndentedString(adjustments)).append("\n");
    sb.append("    utilized: ").append(toIndentedString(utilized)).append("\n");
    sb.append("    serviceOverage: ").append(toIndentedString(serviceOverage)).append("\n");
    sb.append("    chargesBilledSeparately: ").append(toIndentedString(chargesBilledSeparately)).append("\n");
    sb.append("    totalOverage: ").append(toIndentedString(totalOverage)).append("\n");
    sb.append("    totalUsage: ").append(toIndentedString(totalUsage)).append("\n");
    sb.append("    azureMarketplaceServiceCharges: ").append(toIndentedString(azureMarketplaceServiceCharges)).append("\n");
    sb.append("    newPurchasesDetails: ").append(toIndentedString(newPurchasesDetails)).append("\n");
    sb.append("    adjustmentDetails: ").append(toIndentedString(adjustmentDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

