/*
 * Enterprise Reporting APIs (preview)
 * The Reporting APIs enable Enterprise Azure customers to programmatically pull consumption and billing data into preferred data analysis tools. Generate API Key on Enterprise portal and follow the tutorial under Help - Reporting APIs. The first section under this help article explains how to generate\\retrieve the API key for the specified enrollment. <a href=\"https://docs.microsoft.com/en-us/azure/billing/billing-enterprise-api\" data-linktype=\"external\">Billing Enterprise API official documentation</a>
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;

import org.joda.time.DateTime;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * MarketplacePropertiesV1
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-04T20:02:06.353Z")
public class MarketplacePropertiesV1 {
  @SerializedName("id")
  private String id = null;

  @SerializedName("subscriptionGuid")
  private String subscriptionGuid = null;

  @SerializedName("subscriptionName")
  private String subscriptionName = null;

  @SerializedName("meterId")
  private String meterId = null;

  @SerializedName("usageStartDate")
  private DateTime usageStartDate = null;

  @SerializedName("usageEndDate")
  private DateTime usageEndDate = null;

  @SerializedName("offerName")
  private String offerName = null;

  @SerializedName("resourceGroup")
  private String resourceGroup = null;

  @SerializedName("instanceId")
  private String instanceId = null;

  @SerializedName("additionalInfo")
  private String additionalInfo = null;

  @SerializedName("tags")
  private String tags = null;

  @SerializedName("orderNumber")
  private String orderNumber = null;

  @SerializedName("unitOfMeasure")
  private String unitOfMeasure = null;

  @SerializedName("costCenter")
  private String costCenter = null;

  @SerializedName("accountId")
  private Integer accountId = null;

  @SerializedName("accountName")
  private String accountName = null;

  @SerializedName("accountOwnerId")
  private String accountOwnerId = null;

  @SerializedName("departmentId")
  private Integer departmentId = null;

  @SerializedName("departmentName")
  private String departmentName = null;

  @SerializedName("publisherName")
  private String publisherName = null;

  @SerializedName("planName")
  private String planName = null;

  @SerializedName("consumedQuantity")
  private Double consumedQuantity = null;

  @SerializedName("resourceRate")
  private Double resourceRate = null;

  @SerializedName("extendedCost")
  private Double extendedCost = null;

  public MarketplacePropertiesV1 id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public MarketplacePropertiesV1 subscriptionGuid(String subscriptionGuid) {
    this.subscriptionGuid = subscriptionGuid;
    return this;
  }

   /**
   * Get subscriptionGuid
   * @return subscriptionGuid
  **/
  @ApiModelProperty(value = "")
  public String getSubscriptionGuid() {
    return subscriptionGuid;
  }

  public void setSubscriptionGuid(String subscriptionGuid) {
    this.subscriptionGuid = subscriptionGuid;
  }

  public MarketplacePropertiesV1 subscriptionName(String subscriptionName) {
    this.subscriptionName = subscriptionName;
    return this;
  }

   /**
   * Get subscriptionName
   * @return subscriptionName
  **/
  @ApiModelProperty(value = "")
  public String getSubscriptionName() {
    return subscriptionName;
  }

  public void setSubscriptionName(String subscriptionName) {
    this.subscriptionName = subscriptionName;
  }

  public MarketplacePropertiesV1 meterId(String meterId) {
    this.meterId = meterId;
    return this;
  }

   /**
   * Get meterId
   * @return meterId
  **/
  @ApiModelProperty(value = "")
  public String getMeterId() {
    return meterId;
  }

  public void setMeterId(String meterId) {
    this.meterId = meterId;
  }

  public MarketplacePropertiesV1 usageStartDate(DateTime usageStartDate) {
    this.usageStartDate = usageStartDate;
    return this;
  }

   /**
   * Get usageStartDate
   * @return usageStartDate
  **/
  @ApiModelProperty(value = "")
  public DateTime getUsageStartDate() {
    return usageStartDate;
  }

  public void setUsageStartDate(DateTime usageStartDate) {
    this.usageStartDate = usageStartDate;
  }

  public MarketplacePropertiesV1 usageEndDate(DateTime usageEndDate) {
    this.usageEndDate = usageEndDate;
    return this;
  }

   /**
   * Get usageEndDate
   * @return usageEndDate
  **/
  @ApiModelProperty(value = "")
  public DateTime getUsageEndDate() {
    return usageEndDate;
  }

  public void setUsageEndDate(DateTime usageEndDate) {
    this.usageEndDate = usageEndDate;
  }

  public MarketplacePropertiesV1 offerName(String offerName) {
    this.offerName = offerName;
    return this;
  }

   /**
   * Get offerName
   * @return offerName
  **/
  @ApiModelProperty(value = "")
  public String getOfferName() {
    return offerName;
  }

  public void setOfferName(String offerName) {
    this.offerName = offerName;
  }

  public MarketplacePropertiesV1 resourceGroup(String resourceGroup) {
    this.resourceGroup = resourceGroup;
    return this;
  }

   /**
   * Get resourceGroup
   * @return resourceGroup
  **/
  @ApiModelProperty(value = "")
  public String getResourceGroup() {
    return resourceGroup;
  }

  public void setResourceGroup(String resourceGroup) {
    this.resourceGroup = resourceGroup;
  }

  public MarketplacePropertiesV1 instanceId(String instanceId) {
    this.instanceId = instanceId;
    return this;
  }

   /**
   * Get instanceId
   * @return instanceId
  **/
  @ApiModelProperty(value = "")
  public String getInstanceId() {
    return instanceId;
  }

  public void setInstanceId(String instanceId) {
    this.instanceId = instanceId;
  }

  public MarketplacePropertiesV1 additionalInfo(String additionalInfo) {
    this.additionalInfo = additionalInfo;
    return this;
  }

   /**
   * Get additionalInfo
   * @return additionalInfo
  **/
  @ApiModelProperty(value = "")
  public String getAdditionalInfo() {
    return additionalInfo;
  }

  public void setAdditionalInfo(String additionalInfo) {
    this.additionalInfo = additionalInfo;
  }

  public MarketplacePropertiesV1 tags(String tags) {
    this.tags = tags;
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @ApiModelProperty(value = "")
  public String getTags() {
    return tags;
  }

  public void setTags(String tags) {
    this.tags = tags;
  }

  public MarketplacePropertiesV1 orderNumber(String orderNumber) {
    this.orderNumber = orderNumber;
    return this;
  }

   /**
   * Get orderNumber
   * @return orderNumber
  **/
  @ApiModelProperty(value = "")
  public String getOrderNumber() {
    return orderNumber;
  }

  public void setOrderNumber(String orderNumber) {
    this.orderNumber = orderNumber;
  }

  public MarketplacePropertiesV1 unitOfMeasure(String unitOfMeasure) {
    this.unitOfMeasure = unitOfMeasure;
    return this;
  }

   /**
   * Get unitOfMeasure
   * @return unitOfMeasure
  **/
  @ApiModelProperty(value = "")
  public String getUnitOfMeasure() {
    return unitOfMeasure;
  }

  public void setUnitOfMeasure(String unitOfMeasure) {
    this.unitOfMeasure = unitOfMeasure;
  }

  public MarketplacePropertiesV1 costCenter(String costCenter) {
    this.costCenter = costCenter;
    return this;
  }

   /**
   * Get costCenter
   * @return costCenter
  **/
  @ApiModelProperty(value = "")
  public String getCostCenter() {
    return costCenter;
  }

  public void setCostCenter(String costCenter) {
    this.costCenter = costCenter;
  }

  public MarketplacePropertiesV1 accountId(Integer accountId) {
    this.accountId = accountId;
    return this;
  }

   /**
   * Get accountId
   * @return accountId
  **/
  @ApiModelProperty(value = "")
  public Integer getAccountId() {
    return accountId;
  }

  public void setAccountId(Integer accountId) {
    this.accountId = accountId;
  }

  public MarketplacePropertiesV1 accountName(String accountName) {
    this.accountName = accountName;
    return this;
  }

   /**
   * Get accountName
   * @return accountName
  **/
  @ApiModelProperty(value = "")
  public String getAccountName() {
    return accountName;
  }

  public void setAccountName(String accountName) {
    this.accountName = accountName;
  }

  public MarketplacePropertiesV1 accountOwnerId(String accountOwnerId) {
    this.accountOwnerId = accountOwnerId;
    return this;
  }

   /**
   * Get accountOwnerId
   * @return accountOwnerId
  **/
  @ApiModelProperty(value = "")
  public String getAccountOwnerId() {
    return accountOwnerId;
  }

  public void setAccountOwnerId(String accountOwnerId) {
    this.accountOwnerId = accountOwnerId;
  }

  public MarketplacePropertiesV1 departmentId(Integer departmentId) {
    this.departmentId = departmentId;
    return this;
  }

   /**
   * Get departmentId
   * @return departmentId
  **/
  @ApiModelProperty(value = "")
  public Integer getDepartmentId() {
    return departmentId;
  }

  public void setDepartmentId(Integer departmentId) {
    this.departmentId = departmentId;
  }

  public MarketplacePropertiesV1 departmentName(String departmentName) {
    this.departmentName = departmentName;
    return this;
  }

   /**
   * Get departmentName
   * @return departmentName
  **/
  @ApiModelProperty(value = "")
  public String getDepartmentName() {
    return departmentName;
  }

  public void setDepartmentName(String departmentName) {
    this.departmentName = departmentName;
  }

  public MarketplacePropertiesV1 publisherName(String publisherName) {
    this.publisherName = publisherName;
    return this;
  }

   /**
   * Get publisherName
   * @return publisherName
  **/
  @ApiModelProperty(value = "")
  public String getPublisherName() {
    return publisherName;
  }

  public void setPublisherName(String publisherName) {
    this.publisherName = publisherName;
  }

  public MarketplacePropertiesV1 planName(String planName) {
    this.planName = planName;
    return this;
  }

   /**
   * Get planName
   * @return planName
  **/
  @ApiModelProperty(value = "")
  public String getPlanName() {
    return planName;
  }

  public void setPlanName(String planName) {
    this.planName = planName;
  }

  public MarketplacePropertiesV1 consumedQuantity(Double consumedQuantity) {
    this.consumedQuantity = consumedQuantity;
    return this;
  }

   /**
   * Get consumedQuantity
   * @return consumedQuantity
  **/
  @ApiModelProperty(value = "")
  public Double getConsumedQuantity() {
    return consumedQuantity;
  }

  public void setConsumedQuantity(Double consumedQuantity) {
    this.consumedQuantity = consumedQuantity;
  }

  public MarketplacePropertiesV1 resourceRate(Double resourceRate) {
    this.resourceRate = resourceRate;
    return this;
  }

   /**
   * Get resourceRate
   * @return resourceRate
  **/
  @ApiModelProperty(value = "")
  public Double getResourceRate() {
    return resourceRate;
  }

  public void setResourceRate(Double resourceRate) {
    this.resourceRate = resourceRate;
  }

  public MarketplacePropertiesV1 extendedCost(Double extendedCost) {
    this.extendedCost = extendedCost;
    return this;
  }

   /**
   * Get extendedCost
   * @return extendedCost
  **/
  @ApiModelProperty(value = "")
  public Double getExtendedCost() {
    return extendedCost;
  }

  public void setExtendedCost(Double extendedCost) {
    this.extendedCost = extendedCost;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarketplacePropertiesV1 marketplacePropertiesV1 = (MarketplacePropertiesV1) o;
    return Objects.equals(this.id, marketplacePropertiesV1.id) &&
        Objects.equals(this.subscriptionGuid, marketplacePropertiesV1.subscriptionGuid) &&
        Objects.equals(this.subscriptionName, marketplacePropertiesV1.subscriptionName) &&
        Objects.equals(this.meterId, marketplacePropertiesV1.meterId) &&
        Objects.equals(this.usageStartDate, marketplacePropertiesV1.usageStartDate) &&
        Objects.equals(this.usageEndDate, marketplacePropertiesV1.usageEndDate) &&
        Objects.equals(this.offerName, marketplacePropertiesV1.offerName) &&
        Objects.equals(this.resourceGroup, marketplacePropertiesV1.resourceGroup) &&
        Objects.equals(this.instanceId, marketplacePropertiesV1.instanceId) &&
        Objects.equals(this.additionalInfo, marketplacePropertiesV1.additionalInfo) &&
        Objects.equals(this.tags, marketplacePropertiesV1.tags) &&
        Objects.equals(this.orderNumber, marketplacePropertiesV1.orderNumber) &&
        Objects.equals(this.unitOfMeasure, marketplacePropertiesV1.unitOfMeasure) &&
        Objects.equals(this.costCenter, marketplacePropertiesV1.costCenter) &&
        Objects.equals(this.accountId, marketplacePropertiesV1.accountId) &&
        Objects.equals(this.accountName, marketplacePropertiesV1.accountName) &&
        Objects.equals(this.accountOwnerId, marketplacePropertiesV1.accountOwnerId) &&
        Objects.equals(this.departmentId, marketplacePropertiesV1.departmentId) &&
        Objects.equals(this.departmentName, marketplacePropertiesV1.departmentName) &&
        Objects.equals(this.publisherName, marketplacePropertiesV1.publisherName) &&
        Objects.equals(this.planName, marketplacePropertiesV1.planName) &&
        Objects.equals(this.consumedQuantity, marketplacePropertiesV1.consumedQuantity) &&
        Objects.equals(this.resourceRate, marketplacePropertiesV1.resourceRate) &&
        Objects.equals(this.extendedCost, marketplacePropertiesV1.extendedCost);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, subscriptionGuid, subscriptionName, meterId, usageStartDate, usageEndDate, offerName, resourceGroup, instanceId, additionalInfo, tags, orderNumber, unitOfMeasure, costCenter, accountId, accountName, accountOwnerId, departmentId, departmentName, publisherName, planName, consumedQuantity, resourceRate, extendedCost);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarketplacePropertiesV1 {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    subscriptionGuid: ").append(toIndentedString(subscriptionGuid)).append("\n");
    sb.append("    subscriptionName: ").append(toIndentedString(subscriptionName)).append("\n");
    sb.append("    meterId: ").append(toIndentedString(meterId)).append("\n");
    sb.append("    usageStartDate: ").append(toIndentedString(usageStartDate)).append("\n");
    sb.append("    usageEndDate: ").append(toIndentedString(usageEndDate)).append("\n");
    sb.append("    offerName: ").append(toIndentedString(offerName)).append("\n");
    sb.append("    resourceGroup: ").append(toIndentedString(resourceGroup)).append("\n");
    sb.append("    instanceId: ").append(toIndentedString(instanceId)).append("\n");
    sb.append("    additionalInfo: ").append(toIndentedString(additionalInfo)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    orderNumber: ").append(toIndentedString(orderNumber)).append("\n");
    sb.append("    unitOfMeasure: ").append(toIndentedString(unitOfMeasure)).append("\n");
    sb.append("    costCenter: ").append(toIndentedString(costCenter)).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    accountName: ").append(toIndentedString(accountName)).append("\n");
    sb.append("    accountOwnerId: ").append(toIndentedString(accountOwnerId)).append("\n");
    sb.append("    departmentId: ").append(toIndentedString(departmentId)).append("\n");
    sb.append("    departmentName: ").append(toIndentedString(departmentName)).append("\n");
    sb.append("    publisherName: ").append(toIndentedString(publisherName)).append("\n");
    sb.append("    planName: ").append(toIndentedString(planName)).append("\n");
    sb.append("    consumedQuantity: ").append(toIndentedString(consumedQuantity)).append("\n");
    sb.append("    resourceRate: ").append(toIndentedString(resourceRate)).append("\n");
    sb.append("    extendedCost: ").append(toIndentedString(extendedCost)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

