/*
 * Enterprise Reporting APIs (preview)
 * The Reporting APIs enable Enterprise Azure customers to programmatically pull consumption and billing data into preferred data analysis tools. Generate API Key on Enterprise portal and follow the tutorial under Help - Reporting APIs. The first section under this help article explains how to generate\\retrieve the API key for the specified enrollment. <a href=\"https://docs.microsoft.com/en-us/azure/billing/billing-enterprise-api\" data-linktype=\"external\">Billing Enterprise API official documentation</a>
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * PriceSheetV1
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-04T20:02:06.353Z")
public class PriceSheetV1 {
  @SerializedName("id")
  private String id = null;

  @SerializedName("billingPeriodId")
  private String billingPeriodId = null;

  @SerializedName("meterName")
  private String meterName = null;

  @SerializedName("unitOfMeasure")
  private String unitOfMeasure = null;

  @SerializedName("includedQuantity")
  private Double includedQuantity = null;

  @SerializedName("partNumber")
  private String partNumber = null;

  @SerializedName("unitPrice")
  private Double unitPrice = null;

  @SerializedName("currencyCode")
  private String currencyCode = null;

  public PriceSheetV1 id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public PriceSheetV1 billingPeriodId(String billingPeriodId) {
    this.billingPeriodId = billingPeriodId;
    return this;
  }

   /**
   * Get billingPeriodId
   * @return billingPeriodId
  **/
  @ApiModelProperty(value = "")
  public String getBillingPeriodId() {
    return billingPeriodId;
  }

  public void setBillingPeriodId(String billingPeriodId) {
    this.billingPeriodId = billingPeriodId;
  }

  public PriceSheetV1 meterName(String meterName) {
    this.meterName = meterName;
    return this;
  }

   /**
   * Get meterName
   * @return meterName
  **/
  @ApiModelProperty(value = "")
  public String getMeterName() {
    return meterName;
  }

  public void setMeterName(String meterName) {
    this.meterName = meterName;
  }

  public PriceSheetV1 unitOfMeasure(String unitOfMeasure) {
    this.unitOfMeasure = unitOfMeasure;
    return this;
  }

   /**
   * Get unitOfMeasure
   * @return unitOfMeasure
  **/
  @ApiModelProperty(value = "")
  public String getUnitOfMeasure() {
    return unitOfMeasure;
  }

  public void setUnitOfMeasure(String unitOfMeasure) {
    this.unitOfMeasure = unitOfMeasure;
  }

  public PriceSheetV1 includedQuantity(Double includedQuantity) {
    this.includedQuantity = includedQuantity;
    return this;
  }

   /**
   * Get includedQuantity
   * @return includedQuantity
  **/
  @ApiModelProperty(value = "")
  public Double getIncludedQuantity() {
    return includedQuantity;
  }

  public void setIncludedQuantity(Double includedQuantity) {
    this.includedQuantity = includedQuantity;
  }

  public PriceSheetV1 partNumber(String partNumber) {
    this.partNumber = partNumber;
    return this;
  }

   /**
   * Get partNumber
   * @return partNumber
  **/
  @ApiModelProperty(value = "")
  public String getPartNumber() {
    return partNumber;
  }

  public void setPartNumber(String partNumber) {
    this.partNumber = partNumber;
  }

  public PriceSheetV1 unitPrice(Double unitPrice) {
    this.unitPrice = unitPrice;
    return this;
  }

   /**
   * Get unitPrice
   * @return unitPrice
  **/
  @ApiModelProperty(value = "")
  public Double getUnitPrice() {
    return unitPrice;
  }

  public void setUnitPrice(Double unitPrice) {
    this.unitPrice = unitPrice;
  }

  public PriceSheetV1 currencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
    return this;
  }

   /**
   * Get currencyCode
   * @return currencyCode
  **/
  @ApiModelProperty(value = "")
  public String getCurrencyCode() {
    return currencyCode;
  }

  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PriceSheetV1 priceSheetV1 = (PriceSheetV1) o;
    return Objects.equals(this.id, priceSheetV1.id) &&
        Objects.equals(this.billingPeriodId, priceSheetV1.billingPeriodId) &&
        Objects.equals(this.meterName, priceSheetV1.meterName) &&
        Objects.equals(this.unitOfMeasure, priceSheetV1.unitOfMeasure) &&
        Objects.equals(this.includedQuantity, priceSheetV1.includedQuantity) &&
        Objects.equals(this.partNumber, priceSheetV1.partNumber) &&
        Objects.equals(this.unitPrice, priceSheetV1.unitPrice) &&
        Objects.equals(this.currencyCode, priceSheetV1.currencyCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, billingPeriodId, meterName, unitOfMeasure, includedQuantity, partNumber, unitPrice, currencyCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PriceSheetV1 {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    billingPeriodId: ").append(toIndentedString(billingPeriodId)).append("\n");
    sb.append("    meterName: ").append(toIndentedString(meterName)).append("\n");
    sb.append("    unitOfMeasure: ").append(toIndentedString(unitOfMeasure)).append("\n");
    sb.append("    includedQuantity: ").append(toIndentedString(includedQuantity)).append("\n");
    sb.append("    partNumber: ").append(toIndentedString(partNumber)).append("\n");
    sb.append("    unitPrice: ").append(toIndentedString(unitPrice)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

